### PR TITLE
Only rotate the first child icon when accordion is open

### PR DESCRIPTION
**Pull request by codebling**
This is a possible solution for #625.

### CODE REVIEW

**Comment by lu4p** [comment]
@codebling This got merged into the https://github.com/lu4p/specter fork I actively maintain.

**Comment by codebling** [comment]
@lu4p awesome!  I'll check out your fork.  You may want to also have a look at the [comment](https://github.com/picturepan2/spectre/issues/625#issuecomment-628928669) in the linked issue, which proposes an alternative solution.

**Comment by picturepan2** [comment]
@codebling Don't believe @lu4p. I made a quick response #634 .

**Comment by codebling** [comment]
@picturepan2 it's open source. If someone doesn't have time to maintain a product, someone else forks and maintains it. If you are not happy that your name was not preserved as author or that no mention of the original work was made, you should consider opening an issue in lu4p's fork. I'm sure they would be happy to add proper attribution.

**Comment by picturepan2** [comment]
@codebling I am fine with the fork or `LICENSE`. But this genius claims the project was created by it. Sorry, I don't believe a liar and I will not talk to a liar. It might also be good at merging without reviews. Very good job.

**Comment by codebling** [comment]
From project README
> image

**Comment by picturepan2** [comment]
Sorry. Also from README. 
image
Liar is liar. The bottom line is not lying, right? Don't say it is doing good with the LICENSE or note the source. Those are basic things. 

BTW, I am updating Spectre.css to fight against the liar. https://github.com/picturepan2/spectre/releases/tag/v0.5.9 v0.5.9 is the first I can do today. I delayed my full time work and more improvements are coming.

**Pull request merged**
