### PR TITLE
background-color change

### PR DESCRIPTION
**Pull request by szymel2020**
hello
i'm learn github, and i just try how it working, 
if you get this message please tell me that it's fine or not
thanks so much

### CODE REVIEW

**Comment by szymel2020** [comment]
Thank you for your answer. it showed me that I'm learning well. I have a question, can you suggest me something in learning css and javascript, how can I learn?

**Comment by szymel2020** [comment]
Thank you for your answer. it showed me that I'm learning well. I have a question, can you suggest me something in learning css and javascript, how can I learn?

**Comment by picturepan2** [comment]
@szymel2020 https://developer.mozilla.org/en-US/docs/Web MDN Docs is a good place to learn.

**Comment by szymel2020** [comment]
Yan Zhu thanks for your answer.

szymon

czw., 2 lip 2020 o 03:47 Yan Zhu <notifications@github.com> napisał(a):

**Pull request closed without merging**
