### PR TITLE
fix(enhancement): fix text overflow and strict size of button group e…

### PR DESCRIPTION
**Pull request by bricss**
Fix the issue of text overflow and make buttons with a strict width

### CODE REVIEW

**Comment by bricss** [comment]
Is there any chance that this will be merged or I should make it as additional class? 👾

**Comment by picturepan2** [comment]
@bricss Spectre had these styles before. But I removed it (mostly `overflow: hidden;`) for Tooltips support.

**Comment by bricss** [comment]
It wasn't actually about ```overflow: hidden;```, that patch had to fix shrinking size of elements inside ```btn-group``` with different width of text within elements.
I will create another one with new classname ```btn-group-block-fixed```

**Comment by picturepan2** [comment]
@bricss I think this can be done with `flex: 1 0 0;`. Every buttons inside `btn-group` will have same width.

**Comment by roemhildtg** [comment]
@picturepan2 is this issue related to what is happening in this table? https://roemhildtg.github.io/spectre-canjs/list-table/demo/demo.html

**Pull request closed without merging**
