### PR TITLE
Add versions to dist artifacts

### LINKED ISSUE #289: Please add version number in *.min.css
Please add version number in *.min.css, it will help understand which version we're using.

### PR DESCRIPTION
**Pull request by victorparmar**
This PR is to have the dist artifacts versioned to manage upgrades. Closes #289

### CODE REVIEW

**Comment by victorparmar** [comment]
@picturepan2 Any comment on this MR?

**Comment by picturepan2** [comment]
@victorparmar Why do you think this change is necessary?

**Comment by victorparmar** [comment]
As spectre matures, it would be good to offer built in versioning for users to manage updates. I have been using spectre.css in a few projects since 0.3.x and it is getting difficult for me to see which project is using which version.

Of course I can always postfix the version myself but that is an extra step for me to remember and do. Other mature projects such as `jQuery` also come versioned by default!

**Comment by victorparmar** [comment]
@picturepan2 I'm sorry to be a pain in the ass but I have a few projects that are waiting to be updated and it would be great to have versioning built in. Otherwise I will need to make a custom automated solution to generate my own builds.

It would be great if you could let me know if you consider this at all.

Thanks,

**Comment by Geczy** [comment]
Bootstrap versions by adding commented code to the top of their dist

```
/*!
 * Bootstrap v4.0.0-beta (https://getbootstrap.com)
 * Copyright 2011-2017 The Bootstrap Authors
 * Copyright 2011-2017 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
```

Would this work?

**Comment by picturepan2** [comment]
Yes. I can add this after the vacation.

Yan Zhu
________________________________

**Comment by picturepan2** [comment]
@Geczy Version number is added to CSS files in v0.4.4.

**Pull request closed without merging**
