### PR TITLE
calculate video aspect ratio

### PR DESCRIPTION
**Pull request by marcobiedermann**
Calculate video aspect ratio instead of hardcoding values in.

### CODE REVIEW

**Comment by picturepan2** [comment]
I admit CSS is not perfect to do this without JS. But for most YouTube/Youku videos, 16: 9 or 4: 3 are more common ones. People can choose or customize it. But using `padding-bottom: 100%;` means it will be a square video.

**Comment by picturepan2** [comment]
I think I will keep it hardcoded and leave a comment with how to get this padding here. And add the ratio 4:3. Thanks anyway.

**Comment by marcobiedermann** [comment]
I suggest the following setup:

```
.video-responsive {
  padding-bottom: 100% / (16 / 9);
}
```

```
.video-responsive-4-3 {
  padding-bottom: 100% / (4 / 3);
}
```

This way, you have a default aspect ratio of 16:9 which most of the vides fit.
If you need another ratio, just append a second class:
```
<div class="video-responsive video-responsive-4-3"></div>
```

**Comment by picturepan2** [comment]
Done.

**Comment by marcobiedermann** [comment]
Fixed in 9ab261e4f7ae1d0c69c0b479745096f51df3d687

**Pull request closed without merging**
