### PR TITLE
Feature/add new btn-group-fixed class

### PR DESCRIPTION
**Pull request by bricss**
Add new class ```btn-group-fixed``` to make all buttons inside ```btn-group``` of the same width.

### CODE REVIEW

**Comment by bricss** [comment]
@picturepan2 Ping

**Comment by picturepan2** [comment]
@bricss Do you think if it is good idea to make `btn-group-block` buttons same width?

**Comment by bricss** [comment]
@picturepan2 Yep, I think so, because sometimes you may have several button with slightly​ different inner text, but want it to have the similar width, for example like table with fixed layout.

**Comment by picturepan2** [comment]
@bricss I have added `flex: 1 0 0;` to buttons inside a `btn-group-block`, not `btn-group-fixed`. Thank you.

**Pull request closed without merging**
